apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-05-07T05:15:17Z
    generation: 3
    labels:
      app: auditquery
    name: auditquery
    namespace: nos-local
    resourceVersion: "3996988846"
    selfLink: /apis/apps.openshift.io/v1/namespaces/nos-local/deploymentconfigs/auditquery
    uid: 1a34a961-7087-11e9-89b9-1250f17a13c8
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: auditquery
      deploymentconfig: auditquery
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: auditquery
          deploymentconfig: auditquery
      spec:
        containers:
        - image: jind0001/auditquery@sha256:2869115addd35f092b491a44a41c74032f8656946d71384a8cbf074416298b92
          imagePullPolicy: IfNotPresent
          name: auditquery
          ports:
          - containerPort: 8082
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/auditquery/conf
            name: volume-elm3u
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: auditquery-config
          name: volume-elm3u
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - auditquery
        from:
          kind: ImageStreamTag
          name: auditquery:1.11
          namespace: nos-local
        lastTriggeredImage: jind0001/auditquery@sha256:2869115addd35f092b491a44a41c74032f8656946d71384a8cbf074416298b92
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-05-07T05:15:29Z
      lastUpdateTime: 2019-05-07T05:15:29Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2019-05-07T05:16:16Z
      lastUpdateTime: 2019-05-07T05:16:19Z
      message: replication controller "auditquery-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 2
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-05-07T05:11:18Z
    generation: 2
    labels:
      app: indy
    name: indy
    namespace: nos-local
    resourceVersion: "3996982518"
    selfLink: /apis/apps.openshift.io/v1/namespaces/nos-local/deploymentconfigs/indy
    uid: 8befe302-7086-11e9-89b9-1250f17a13c8
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: indy
      deploymentconfig: indy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: indy
          deploymentconfig: indy
      spec:
        containers:
        - image: jind0001/indy@sha256:7aba9eba6353c2fe36b228ddb130f39a610c52eaa9d22e5cea09acfc65327a24
          imagePullPolicy: IfNotPresent
          name: indy
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - indy
        from:
          kind: ImageStreamTag
          name: indy:1.6
          namespace: nos-local
        lastTriggeredImage: jind0001/indy@sha256:7aba9eba6353c2fe36b228ddb130f39a610c52eaa9d22e5cea09acfc65327a24
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-05-07T05:11:35Z
      lastUpdateTime: 2019-05-07T05:11:35Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2019-05-07T05:11:22Z
      lastUpdateTime: 2019-05-07T05:11:38Z
      message: replication controller "indy-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-05-07T05:11:19Z
    generation: 2
    labels:
      app: jgroups-gossip
    name: jgroups-gossip
    namespace: nos-local
    resourceVersion: "3996982458"
    selfLink: /apis/apps.openshift.io/v1/namespaces/nos-local/deploymentconfigs/jgroups-gossip
    uid: 8c1e0877-7086-11e9-89b9-1250f17a13c8
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: jgroups-gossip
      deploymentconfig: jgroups-gossip
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: jgroups-gossip
          deploymentconfig: jgroups-gossip
      spec:
        containers:
        - env:
          - name: LogLevel
            value: trace
          image: jboss/jgroups-gossip@sha256:6f51b5261f65e39c555dc8ac4b08aaade7421ff7db330e83f2e24385ff571d22
          imagePullPolicy: Always
          name: jgroups-gossip
          ports:
          - containerPort: 12001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jgroups-gossip
        from:
          kind: ImageStreamTag
          name: jgroups-gossip:latest
          namespace: nos-local
        lastTriggeredImage: jboss/jgroups-gossip@sha256:6f51b5261f65e39c555dc8ac4b08aaade7421ff7db330e83f2e24385ff571d22
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-05-07T05:11:34Z
      lastUpdateTime: 2019-05-07T05:11:34Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2019-05-07T05:11:35Z
      lastUpdateTime: 2019-05-07T05:11:35Z
      message: replication controller "jgroups-gossip-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
