apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-04-26T03:27:26Z
    generation: 2
    labels:
      app: auditquery
    name: auditquery
    namespace: nos-local
    resourceVersion: "3977998391"
    selfLink: /apis/apps.openshift.io/v1/namespaces/nos-local/deploymentconfigs/auditquery
    uid: 36954a85-67d3-11e9-8eba-1250f17a13c8
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: auditquery
      deploymentconfig: auditquery
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: auditquery
          deploymentconfig: auditquery
      spec:
        containers:
        - image: jind0001/auditquery@sha256:7897013f375910335993aa9e73c28db6040c9dc4b668fc738cb7d8035223c7e1
          imagePullPolicy: IfNotPresent
          name: auditquery
          ports:
          - containerPort: 8082
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/auditquery/etc/auditquery
            name: volume-6dxcy
          - mountPath: /opt/auditquery/etc/auditquery/logging
            name: volume-kzbmp
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: auditquery-config
          name: volume-6dxcy
        - configMap:
            defaultMode: 420
            name: auditquery-logging-config
          name: volume-kzbmp
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - auditquery
        from:
          kind: ImageStreamTag
          name: auditquery:1.9
          namespace: nos-local
        lastTriggeredImage: jind0001/auditquery@sha256:7897013f375910335993aa9e73c28db6040c9dc4b668fc738cb7d8035223c7e1
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-04-26T03:27:36Z
      lastUpdateTime: 2019-04-26T03:27:36Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2019-04-26T03:27:32Z
      lastUpdateTime: 2019-04-26T03:27:37Z
      message: replication controller "auditquery-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-04-26T03:27:26Z
    generation: 2
    labels:
      app: indy
    name: indy
    namespace: nos-local
    resourceVersion: "3977998303"
    selfLink: /apis/apps.openshift.io/v1/namespaces/nos-local/deploymentconfigs/indy
    uid: 36bab3e3-67d3-11e9-8eba-1250f17a13c8
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: indy
      deploymentconfig: indy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: indy
          deploymentconfig: indy
      spec:
        containers:
        - image: jind0001/indy@sha256:7aba9eba6353c2fe36b228ddb130f39a610c52eaa9d22e5cea09acfc65327a24
          imagePullPolicy: IfNotPresent
          name: indy
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - indy
        from:
          kind: ImageStreamTag
          name: indy:1.6
          namespace: nos-local
        lastTriggeredImage: jind0001/indy@sha256:7aba9eba6353c2fe36b228ddb130f39a610c52eaa9d22e5cea09acfc65327a24
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-04-26T03:27:35Z
      lastUpdateTime: 2019-04-26T03:27:35Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2019-04-26T03:27:32Z
      lastUpdateTime: 2019-04-26T03:27:35Z
      message: replication controller "indy-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-04-26T03:27:26Z
    generation: 2
    labels:
      app: jgroups-gossip
    name: jgroups-gossip
    namespace: nos-local
    resourceVersion: "3977998444"
    selfLink: /apis/apps.openshift.io/v1/namespaces/nos-local/deploymentconfigs/jgroups-gossip
    uid: 36e0011d-67d3-11e9-8eba-1250f17a13c8
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: jgroups-gossip
      deploymentconfig: jgroups-gossip
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: jgroups-gossip
          deploymentconfig: jgroups-gossip
      spec:
        containers:
        - env:
          - name: LogLevel
            value: trace
          image: jboss/jgroups-gossip@sha256:6f51b5261f65e39c555dc8ac4b08aaade7421ff7db330e83f2e24385ff571d22
          imagePullPolicy: Always
          name: jgroups-gossip
          ports:
          - containerPort: 12001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jgroups-gossip
        from:
          kind: ImageStreamTag
          name: jgroups-gossip:latest
          namespace: nos-local
        lastTriggeredImage: jboss/jgroups-gossip@sha256:6f51b5261f65e39c555dc8ac4b08aaade7421ff7db330e83f2e24385ff571d22
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-04-26T03:27:38Z
      lastUpdateTime: 2019-04-26T03:27:38Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2019-04-26T03:27:40Z
      lastUpdateTime: 2019-04-26T03:27:40Z
      message: replication controller "jgroups-gossip-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
