apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-05-06T06:46:13Z
    labels:
      app: auditquery
    name: auditquery
    namespace: nos-local
    resourceVersion: "3995331874"
    selfLink: /api/v1/namespaces/nos-local/services/auditquery
    uid: a3f1d440-6fca-11e9-b419-122631632f42
  spec:
    clusterIP: 172.30.14.117
    ports:
    - name: 8082-tcp
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: auditquery
      deploymentconfig: auditquery
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-04-28T05:17:28Z
    labels:
      app: indy
    name: indy
    namespace: nos-local
    resourceVersion: "3981797164"
    selfLink: /api/v1/namespaces/nos-local/services/indy
    uid: ea715c3f-6974-11e9-8eba-1250f17a13c8
  spec:
    clusterIP: 172.30.68.250
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: indy
      deploymentconfig: indy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-04-28T05:17:28Z
    labels:
      app: jgroups-gossip
    name: jgroups-gossip
    namespace: nos-local
    resourceVersion: "3981797177"
    selfLink: /api/v1/namespaces/nos-local/services/jgroups-gossip
    uid: eaa41d77-6974-11e9-8eba-1250f17a13c8
  spec:
    clusterIP: 172.30.140.116
    ports:
    - name: 12001-tcp
      port: 12001
      protocol: TCP
      targetPort: 12001
    selector:
      app: jgroups-gossip
      deploymentconfig: jgroups-gossip
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
