apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-04-26T03:27:28Z
    labels:
      app: auditquery
    name: auditquery
    namespace: nos-local
    resourceVersion: "3977998088"
    selfLink: /api/v1/namespaces/nos-local/services/auditquery
    uid: 37ec0164-67d3-11e9-8967-122631632f42
  spec:
    clusterIP: 172.30.206.221
    ports:
    - name: 8082-tcp
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: auditquery
      deploymentconfig: auditquery
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-04-26T03:27:28Z
    labels:
      app: indy
    name: indy
    namespace: nos-local
    resourceVersion: "3977998102"
    selfLink: /api/v1/namespaces/nos-local/services/indy
    uid: 381361e7-67d3-11e9-8967-122631632f42
  spec:
    clusterIP: 172.30.68.250
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: indy
      deploymentconfig: indy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-04-26T03:27:29Z
    labels:
      app: jgroups-gossip
    name: jgroups-gossip
    namespace: nos-local
    resourceVersion: "3977998110"
    selfLink: /api/v1/namespaces/nos-local/services/jgroups-gossip
    uid: 384ab40c-67d3-11e9-8967-122631632f42
  spec:
    clusterIP: 172.30.140.116
    ports:
    - name: 12001-tcp
      port: 12001
      protocol: TCP
      targetPort: 12001
    selector:
      app: jgroups-gossip
      deploymentconfig: jgroups-gossip
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
