apiVersion: v1
data:
  infinispan-cluster.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:9.4 http://www.infinispan.org/schemas/infinispan-config-9.4.xsd"
            xmlns="urn:infinispan:config:9.4">

        <jgroups>
            <stack-file name="external-file" path="/opt/jboss/auditquery/etc/auditquery/jgroups-tcp.xml" />
        </jgroups>

        <cache-container default-cache="event-audit" name="auditQueryClusterCacheManager">
            <transport stack="external-file" cluster="default"/>

            <replicated-cache name="event-audit">
                <indexing index="LOCAL">
                    <property name="default.directory_provider">local-heap</property>
                </indexing>
            </replicated-cache>

        </cache-container>

    </infinispan>
  infinispan.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:9.4 http://www.infinispan.org/schemas/infinispan-config-9.4.xsd"
            xmlns="urn:infinispan:config:9.4">

        <cache-container default-cache="default" name="auditQueryCacheManager">
            <!-- template configurations -->
            <local-cache-configuration name="local-template">
                <memory>
                    <object size="20000" strategy="REMOVE"/>
                </memory>
            </local-cache-configuration>

            <local-cache name="default" configuration="local-template"/>

            <local-cache name="tracking_summary_cache" configuration="local-template">
                <indexing index="LOCAL">
                    <property name="default.directory_provider">ram</property>
                </indexing>
            </local-cache>

            <local-cache name="tracked_content_dto_cache" configuration="local-template">
                <indexing index="LOCAL">
                    <property name="default.directory_provider">ram</property>
                </indexing>
            </local-cache>
        </cache-container>

    </infinispan>
  jgroups-tcp.xml: |-
    <config xmlns="urn:org:jgroups"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups-4.0.xsd">

        <TCP
                bind_port="${jgroups.tcp.bind_port}"
                enable_diagnostics="false"
                thread_naming_pattern="pl"
                send_buf_size="640k"
                sock_conn_timeout="30000"
                bundler_type="no-bundler"

                thread_pool.min_threads="${jgroups.thread_pool.min_threads:0}"
                thread_pool.max_threads="${jgroups.thread_pool.max_threads:200}"
                thread_pool.keep_alive_time="60000"
        />
        <TCPGOSSIP initial_hosts="jgroups-gossip.nos-local.svc.cluster.local[12001]"/>
        <!--
        <TUNNEL gossip_router_hosts="10.128.18.192[12001]:HostA[12001],HostB[12001]" />
        <PING />
        -->
        <!--
        <TCP
         bind_addr="loopback,match-interface:eth0"
         bind_port="7800"
      />
      <org.jgroups.protocols.kubernetes.KUBE_PING
         port_range="1"
      />
    -->
        <MERGE3 min_interval="10000"
                max_interval="30000"
        />
        <FD_SOCK />
        <!-- Suspect node `timeout` to `timeout + timeout_check_interval` millis after the last heartbeat -->
        <FD_ALL timeout="10000"
                interval="2000"
                timeout_check_interval="100000"
        />
        <VERIFY_SUSPECT timeout="1000"/>
        <pbcast.NAKACK2 use_mcast_xmit="false"
                        xmit_interval="100"
                        xmit_table_num_rows="50"
                        xmit_table_msgs_per_row="1024"
                        xmit_table_max_compaction_time="30000"
                        resend_last_seqno="true"
        />
        <UNICAST3 xmit_interval="100"
                  xmit_table_num_rows="50"
                  xmit_table_msgs_per_row="1024"
                  xmit_table_max_compaction_time="30000"
        />
        <pbcast.STABLE stability_delay="500"
                       desired_avg_gossip="5000"
                       max_bytes="1M"
        />
        <pbcast.GMS print_local_addr="false"
                    join_timeout="${jgroups.join_timeout:5000}"
        />
        <MFC max_credits="2m"
             min_threshold="0.40"
        />
        <FRAG3/>
    </config>
  main.conf: |
    # API version

    config.dir=${auditquery.home}/etc/auditquery/

    [ui]
    ui.dir=${auditquery.home}/var/lib/auditquery/ui
    enabled=true

    [rest]
    # indy.url=

    [infinispan-cluster]

    # JGroups gossip router host list, i.e.: HostA[12001],HostB[12001]
    #
    # jgroups.gossip_router_hosts="172.30.180.203[12001]"

    # By default, the tcp bind port for jgroups is 7800
    #
    jgroups.tcp.bind_port=7800
kind: ConfigMap
metadata:
  creationTimestamp: '2019-04-22T05:30:14Z'
  name: auditquery-config
  namespace: nos-local
  resourceVersion: '3970728926'
  selfLink: /api/v1/namespaces/nos-local/configmaps/auditquery-config
  uid: b4bcd484-64bf-11e9-b371-12d641ec7610

