apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: auditquery
    name: auditquery
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: auditquery
      deploymentconfig: auditquery
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: auditquery
          deploymentconfig: auditquery
      spec:
        containers:
        - image: jind0001/auditquery:1.11
          imagePullPolicy: IfNotPresent
          name: auditquery
          ports:
          - containerPort: 8082
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/auditquery/conf
            name: volume-21k3c
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: auditquery-config
          name: volume-21k3c
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - auditquery
        from:
          kind: ImageStreamTag
          name: auditquery:1.11
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: indy
    name: indy
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: indy
      deploymentconfig: indy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: indy
          deploymentconfig: indy
      spec:
        containers:
        - image: jind0001/indy:1.6
          imagePullPolicy: IfNotPresent
          name: indy
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - indy
        from:
          kind: ImageStreamTag
          name: indy:1.6
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: jgroups-gossip
    name: jgroups-gossip
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: jgroups-gossip
      deploymentconfig: jgroups-gossip
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: jgroups-gossip
          deploymentconfig: jgroups-gossip
      spec:
        containers:
        - env:
          - name: LogLevel
            value: trace
          image: jboss/jgroups-gossip:latest
          imagePullPolicy: Always
          name: jgroups-gossip
          ports:
          - containerPort: 12001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jgroups-gossip
        from:
          kind: ImageStreamTag
          name: jgroups-gossip:latest
          namespace: nos-local
      type: ImageChange
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
