apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: auditquery
    name: auditquery
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: jind0001/auditquery:1.11
      from:
        kind: DockerImage
        name: jind0001/auditquery:1.11
      importPolicy: {}
      name: "1.11"
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: openshift-play
    name: base-jdk
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: jboss/base-jdk:8
      from:
        kind: DockerImage
        name: jboss/base-jdk:8
      importPolicy: {}
      name: "8"
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: indy
    name: indy
    namespace: nos-local
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: jind0001/indy:1.6
      from:
        kind: DockerImage
        name: jind0001/indy:1.6
      importPolicy: {}
      name: "1.6"
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: jgroups-gossip
    name: jgroups-gossip
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: jboss/jgroups-gossip
      from:
        kind: DockerImage
        name: jboss/jgroups-gossip
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
