apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: auditquery
    name: auditquery
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: auditquery
      deploymentconfig: auditquery
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: auditquery
          deploymentconfig: auditquery
      spec:
        containers:
        - image: jind0001/auditquery
          imagePullPolicy: IfNotPresent
          name: auditquery
          ports:
          - containerPort: 8082
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/auditquery/conf
            name: volume-elm3u
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: auditquery-config
          name: volume-elm3u
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - auditquery
        from:
          kind: ImageStreamTag
          name: auditquery:1.11
