apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: indy
    name: indy
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: indy
      deploymentconfig: indy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: indy
          deploymentconfig: indy
      spec:
        containers:
        - image: jind0001/indy
          imagePullPolicy: IfNotPresent
          name: indy
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - indy
        from:
          kind: ImageStreamTag
          name: indy:1.6
      type: ImageChange
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
