apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jgroups-gossip
    name: jgroups-gossip
  spec:
    ports:
    - name: 12001-tcp
      port: 12001
      protocol: TCP
      targetPort: 12001
    selector:
      app: jgroups-gossip
      deploymentconfig: jgroups-gossip
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
