apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: indy
    name: indy
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: indy
      deploymentconfig: indy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
